### PR TITLE
Customizing ImageLoading mechanism. (Issue #10)

### PR DESCRIPTION
**Pull request by R4md4c**
[Review on Reviewable](https://reviewable.io/reviews/halysongoncalves/pugnotification/11)

### CODE REVIEW

**Comment by halysongoncalves** [comment]
Hello,

Do not you think feasible leave a default implementation. If you do not pass a ImageLoader the bilbioteca show notification using the Picasso. Only one doubt as user :)

**Comment by R4md4c** [comment]
Well, If we did that we'd still add Picasso as a dependency, and that would add to the apk size and the apk dex limit, right ? If yes, that would be a problem I guess.

Please correct me If I'm wrong.

**Comment by halysongoncalves** [comment]
Hello,

You're right, best left up to the user library of choice for image upload!

**Comment by halysongoncalves** [comment]
Was performed merge regarding codified. Until tomorrow I will climb the new artifact to the central maven!

Thanks for PR!

**Comment by R4md4c** [comment]
Thanks to you for reviewing !

**Comment by halysongoncalves** [comment]
Hello,

After a long vacation time I am again with all gas to develop new features for the library.

And gladly come to inform you that your changes were submitted in release 1.1.0 and is now available in the central maven.

**Pull request merged**
